[package]
name = "second_c"
version = "0.1.0"
edition = "2021"

[dependencies]
petgraph = "0.6"
clap = { version = "4.3.4", features = ["derive"] }
csv = "1.1.6"
rand = "0.8.5"

[[bin]]
name = "second_c"
path = "src/main.rs"

[lib]
name = "fruit_salad_maker"
path = "src/lib.rs"